refactor(dytoy): misc logic

diff --git a/home/dot_config/dytoy/executable_binary.sh.tmpl b/home/dot_config/dytoy/executable_binary.sh.tmpl
--- a/home/dot_config/dytoy/executable_binary.sh.tmpl
+++ b/home/dot_config/dytoy/executable_binary.sh.tmpl
@@ -4,7 +4,7 @@ source {{ .chezmoi.sourceDir }}/../scripts/message.sh
 TEMP_COMPRESSED=$(mktemp)
 TEMP_HOOK_AFTER=$(mktemp)
 TEMP_HOOK_BEFORE=$(mktemp)
-trap "rm -rf $TEMP_COMPRESSED $TEMP_HOOK_BEFORE $TEMP_HOOK_AFTER" ERR
+trap "rm -rf $TEMP_COMPRESSED $TEMP_HOOK_BEFORE $TEMP_HOOK_AFTER && echo \"Install tools failed\"" ERR
 
 SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
 export BIN_DIR=$HOME/.local/bin
@@ -28,7 +28,7 @@ _parse_args() {
         _usage
         ;;
       t) # Only one specific tool
-        PACKAGE=$OPTARG
+        TOOL=$OPTARG
         ;;
       d) # Debug mode
         DEBUG=true
@@ -66,13 +66,13 @@ _extract_tar() {
   if [ "$DEBUG" = true ]; then
     tar ${param}
   else
-    bash $TEMP_HOOK_BEFORE
+    {{ lookPath "bash" }} $TEMP_HOOK_BEFORE
     readarray paths < <(echo "$2" | yq e -o=j -I=0 -r '.[]')
     for path in "${paths[@]}"; do
       tar ${param} -C "$BIN_DIR" $(echo ${path%%*( )} | sed "s/%v/${version}/g" | sed "s/%1v/${version:1}/g")
     done
     export param=$param
-    bash $TEMP_HOOK_AFTER
+    {{ lookPath "bash" }} $TEMP_HOOK_AFTER
   fi
 }
 
@@ -83,12 +83,12 @@ _extract_zip() {
   if [ "$DEBUG" = true ]; then
     unzip -Zl $TEMP_COMPRESSED
   else
-    bash $TEMP_HOOK_BEFORE
+    {{ lookPath "bash" }} $TEMP_HOOK_BEFORE
     readarray paths < <(echo "$2" | yq e -o=j -I=0 -r '.[]')
     for path in "${paths[@]}"; do
       unzip -qqoj $TEMP_COMPRESSED -d $BIN_DIR $(echo ${path%%*( )} | sed "s/%v/${version}/g" | sed "s/%1v/${version:1}/g")
     done
-    bash $TEMP_HOOK_AFTER
+    {{ lookPath "bash" }} $TEMP_HOOK_AFTER
   fi
 }
 
@@ -96,10 +96,10 @@ _extract_zip() {
 # $1: URL of file
 # $2: File name of command
 _extract_bzip2() {
-  bash $TEMP_HOOK_BEFORE
+  {{ lookPath "bash" }} $TEMP_HOOK_BEFORE
   readarray paths < <(echo "$2" | yq e -o=j -I=0 -r '.[]')
   bzip2 -cd $TEMP_COMPRESSED > $BIN_DIR/$2
-  bash $TEMP_HOOK_AFTER
+  {{ lookPath "bash" }} $TEMP_HOOK_AFTER
 }
 
 # Update tool by get from release file
@@ -137,22 +137,22 @@ _update() {
 # by get from Github release file
 # $1: YAML string of tool
 _parse_github_release() {
-  name=$(echo "$package" | yq e '.name')
+  name=$(echo "$1" | yq e '.name')
   if [ "$FLAG_NOT_EXIST" = true ] && [ -f "$BIN_DIR/$name" ]; then
     return
   fi
 
-  is_essential=$(echo "$package" | yq e '.is_essential')
+  is_essential=$(echo "$1" | yq e '.is_essential')
   if [ "$FLAG_IS_ESSENTIAL" = true ] && [ "$is_essential" != "true" ]; then
     return
   fi
 
   _progress "Installing ${name}"
-  repo=$(echo "$package" | yq e '.github.repo')
-  version=$(echo "$package" | yq e '.github.version')
-  release_asset=$(echo "$package" | yq e '.github.release_asset')
-  strip_components=$(echo "$package" | yq e '.archive.strip_components')
-  paths=$(echo "$package" | yq e '.archive.paths')
+  repo=$(echo "$1" | yq e '.github.repo')
+  version=$(echo "$1" | yq e '.github.version')
+  release_asset=$(echo "$1" | yq e '.github.release_asset')
+  strip_components=$(echo "$1" | yq e '.archive.strip_components')
+  paths=$(echo "$1" | yq e '.archive.paths')
 
   _progress "Checking ${name} from ${repo}"
   if [ "$version" = "latest" ] || [ "$version" = "null" ]; then
@@ -189,27 +189,27 @@ _parse_github_release() {
 # by get from Gitlab release file
 # $1: YAML string of tool
 _parse_gitlab_release() {
-  name=$(echo "$package" | yq e '.name')
+  name=$(echo "$1" | yq e '.name')
   if [ "$FLAG_NOT_EXIST" = true ] && [ -f "$BIN_DIR/$name" ]; then
     return
   fi
 
-  is_essential=$(echo "$package" | yq e '.is_essential')
+  is_essential=$(echo "$1" | yq e '.is_essential')
   if [ "$FLAG_IS_ESSENTIAL" = true ] && [ "$is_essential" != "true" ]; then
     return
   fi
 
   _progress "Installing ${name}"
-  host=$(echo "$package" | yq e '.gitlab.host')
+  host=$(echo "$1" | yq e '.gitlab.host')
   if [ "$host" = "null" ]; then
     host="gitlab.com"
   fi
 
-  repo=$(echo "$package" | yq e '.gitlab.repo')
-  version=$(echo "$package" | yq e '.gitlab.version')
-  release_asset=$(echo "$package" | yq e '.gitlab.release_asset')
-  strip_components=$(echo "$package" | yq e '.archive.strip_components')
-  paths=$(echo "$package" | yq e '.archive.paths')
+  repo=$(echo "$1" | yq e '.gitlab.repo')
+  version=$(echo "$1" | yq e '.gitlab.version')
+  release_asset=$(echo "$1" | yq e '.gitlab.release_asset')
+  strip_components=$(echo "$1" | yq e '.archive.strip_components')
+  paths=$(echo "$1" | yq e '.archive.paths')
 
   _progress "Checking ${name} from ${repo}"
   if [ "$version" = "latest" ]; then
@@ -243,26 +243,26 @@ _parse_gitlab_release() {
 }
 
 _main() {
-  if [ "$PACKAGE" = "" ]; then
+  if [ "$TOOL" = "" ]; then
     _info "Install binary tools"
   else
-    _info "Install binary tool: $PACKAGE"
+    _info "Install binary tool: $TOOL"
   fi
-  readarray package_tools < <(yq e -o=j -I=0 'filter(.method == "binary") | .[]' ~/.config/dytoy/tools.yaml )
-  for package in "${package_tools[@]}"; do
-    name=$(echo "$package" | yq e '.name')
-    if [ "$PACKAGE" = "" ] || [ "$PACKAGE" = "$name" ]; then
-      if [ "$(echo "$package" | yq e '.github')" != "null" ]; then
-        _parse_github_release "$package"
-      elif [ "$(echo "$package" | yq e '.gitlab')" != "null" ]; then
-        _parse_gitlab_release "$package"
+  readarray binary_tools < <(yq e -o=j -I=0 'filter(.method == "binary") | .[]' ~/.config/dytoy/tools.yaml )
+  for binary in "${binary_tools[@]}"; do
+    name=$(echo "$binary" | yq e '.name')
+    if [ "$TOOL" = "" ] || [ "$TOOL" = "$name" ]; then
+      if [ "$(echo "$binary" | yq e '.github')" != "null" ]; then
+        _parse_github_release "$binary"
+      elif [ "$(echo "$binary" | yq e '.gitlab')" != "null" ]; then
+        _parse_gitlab_release "$binary"
       fi
     fi
   done
   _success "Installed binary tools"
 }
 
-PACKAGE=
+TOOL=
 FLAG_IS_ESSENTIAL=false
 FLAG_NOT_EXIST=false
 DEBUG=false
